services:
  nginx:
     image: nginx:latest
     container_name: reverse_proxy
     volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
         - ./nginx/templates:/etc/nginx/templates
         - ./container_logs/nginx:/var/log/nginx
         - ./public_html:/usr/share/nginx/html
#          - ./secrets/nginx:/etc/ssl
     ports:
         - "80:80"
#         - "443:443"
     environment:
        - NGINX_PORT=80
        - NGINX_PROXY=http://application:3000
#        - NGINX_CERT_DIR=/etc/ssl
#        - NGINX_SSL_PORT=443
#        - NGINX_ENTRYPOINT_QUIET_LOGS=1
     depends_on:
         - application
     restart: always

  application:
    image: wolke 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/
    command: "npm start"
